import { Injectable } from '@angular/core';
import { ITvshows } from '../interfaces/tvShow';

@Injectable({
  providedIn: 'root'
})
export class TvShowsService {
tvShows: ITvshows[] = [
  {
    name: 'TFou',
    start: 1726812000,
    end: 1726815300,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/7AB87A40F79D0CFCEABA39BB15949652.jpg',
    rating: 'Tout public',
    cat: 'Magazine',
    desc: 'Molang / Ernest & Rebecca (ST) / Robin des bois (ST) / Barbapapa en Famille (ST)',
  },
  {
    "name": "JT 20h",
    "start": 1726862400,
    "end": 1726865100,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/AB67E0AC40E6D75EEB783F5DF6206AF3.jpg",
    "rating": "Tout public",
    "cat": "Information",
    "desc": "\\\" JT 20h WE \\\" du vendredi 20 septembre 2024 à 19h58. Le vendredi à 20h, le samedi et le dimanche, \"LE WE\" prend le relais des journaux de la semaine (\"LE 13H\" et \"LE 20H\"). La rédaction TF1, à travers le jt du weekend continue de vous informer et ainsi met en exergue l'actualité régionale, nationale et internationale. Le journal du weekend est présenté par Audrey Crespo-Mara"
    },
    {
    "name": "My Million",
    "start": 1726865100,
    "end": 1726865400,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/0455568DF04F634E6E2840BCF12A7E84.jpg",
    "rating": "Tout public",
    "cat": "Services",
    "desc": "Au menu, les derniers résultats d'EuroMillions ainsi que les codes gagnants My Million, avec les 5 numéros gagnants et les 2 bonnes étoiles de la loterie."
    },
    {
    "name": "Petits plats en équilibre",
    "start": 1726865400,
    "end": 1726866000,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/F4A4D49AED9904E7ACC78D1FBB8A6CE0.jpg",
    "rating": "Tout public",
    "cat": "Art de vivre",
    "desc": "Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison."
    },
    {
    "name": "Météo",
    "start": 1726866000,
    "end": 1726866600,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/5BCD0442D4813EB2EDCBD3E853A866FE.jpg",
    "rating": "Tout public",
    "cat": "Services",
    "desc": "Météo du vendredi 20 septembre 2024 à 20h46 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du vendredi 20 septembre 2024 à 20h46 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse."
    },
    {
    "name": "Qui veut gagner des millions ?",
    "start": 1726866600,
    "end": 1726877580,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/3B4EF40875F2238E824E44853472B425.jpg",
    "rating": "Tout public",
    "cat": "Divertissement",
    "desc": "Le célèbre jeu \"Qui veut gagner des millions ?\" fête ses 25 ans avec deux émissions spéciales qui promettent leur lot de suspense. Ce soir, les invités sont : Florence Foresti, Joël Dicker, Jean-Pierre Foucault, Jean-Luc Lemoine, Jarry, Kev Adams, Philippe Caverivière, Léa Salamé, Michel Boujenah et Jeff Panacloc."
    },
    {
    "name": "Tirage de l'EuroMillions",
    "start": 1726877580,
    "end": 1726877700,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/4174E38F0D9C2DB2DC75A7C74760178C.jpg",
    "rating": "Tout public",
    "cat": "Services",
    "desc": "Aucune description"
    },
    {
    "name": "Vendredi, tout est permis avec Arthur",
    "start": 1726877700,
    "end": 1726884600,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/F243177C314D2932554FF54B482E69AC.jpg",
    "rating": "Tout public",
    "cat": "Programme",
    "desc": "Arthur vous donne rendez-vous pour une soirée de Vendredi tout est permis ! Au programme de grands moments de rires, le tout en compagnie d'invités exceptionnels ! Séquences culte en perspective ! Vous l'aurez compris, ce vendredi encore, tout est permis et la bonne humeur, garantie !"
    },
    {
    "name": "Programmes de la nuit",
    "start": 1726884600,
    "end": 1726898400,
    "channel": "TF1.fr",
    "icon": "https://img.bouygtel.fr/CMS/images/16467FF15CA52DAAF421F32BFABCF257.jpg",
    "rating": "Tout public",
    "cat": "Programme",
    "desc": "A suivre, des rediffusions des émissions de la chaîne, ainsi que des documentaires et autres reportages destinés à divertir les couche-tard comme les lève-tôt."
    }
  ,
  {
    name: 'Bonjour ! La Matinale TF1',
    start: 1726815300,
    end: 1726824900,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/9B4B92251BA9C1AF8E731359435A58CF.jpg',
    rating: 'Tout public',
    cat: 'Magazine',
    desc: '"Bonjour ! La Matinale TF1" est le premier rendez-vous d\'information de la journée. Bruce Toussaint fait aussi intervenir les correspondants en direct en région.',
  },
  {
    name: 'Téléshopping',
    start: 1726824900,
    end: 1726828200,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/AF5D6F7FA1241092974721F08DA95B8E.jpg',
    rating: 'Tout public',
    cat: 'Services',
    desc: "Le magazine de la consommation et des conseils d'achat, coaché par Marie-Ange Nardi et Alexandre Devoise.",
  },
  {
    name: 'Amour, gloire et beauté',
    start: 1726828200,
    end: 1726830000,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/DB843C065CA3B3466B37C3DF67A90F74.jpg',
    rating: 'Tout public',
    cat: 'Série',
    desc: "Hope et Finn partagent un moment d'émotion. Finn répète que Hope mérite mieux que Thomas.Deacon promet d'aider Sheila à se faire un nouveau nom chez les Forresters.",
  },
  {
    name: "Les Feux de l'amour",
    start: 1726830000,
    end: 1726832700,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/9E4E5E0CCF07E75FC994BFC9BDC137BB.jpg',
    rating: 'Tout public',
    cat: 'Série',
    desc: "La famille Abbott, installée à Genoa City, dans le Wisconsin, possède une immense fortune et une gigantesque entreprise. Les luttes de pouvoir, trahisons au sein même du clan sont monnaie courante. Leur ennemi de toujours, l'industriel Victor Newman, ne fait rien pour leur faciliter la tâche, bien au contraire. D'alliances en ruptures, les illusions de chacun se heurtent à l'hostilité, à la jalousie et à la haine des autres. Entre amour et pouvoir, le choix est souvent celui de la puissance. Un Soap Opera mondialement célèbre, produit et diffusé depuis plus de quarante ans aux Etats-Unis ! A ce jour, une trentaine de pays différents diffusent le feuilleton chaque jour, et c'est en France que le feuilleton réalise ses meilleures audiences, juste derrière les Etats-Unis.",
  },
  {
    name: 'Petits plats en équilibre',
    start: 1726832700,
    end: 1726833000,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/F4A4D49AED9904E7ACC78D1FBB8A6CE0.jpg',
    rating: 'Tout public',
    cat: 'Art de vivre',
    desc: 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.',
  },
  {
    name: 'Les douze coups de midi',
    start: 1726833000,
    end: 1726836900,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/492065E4AD3F78FCE2E60E03C32D8083.jpg',
    rating: 'Tout public',
    cat: 'Divertissement',
    desc: "Emission du 20 septembre 2024 - Chaque jour, quatre candidats s'affrontent pour empocher les 30 000 euros de la cagnotte et décrocher l'étoile mystérieuse et ses cadeaux. Seule condition, bien répondre aux questions de culture générale posées par...",
  },
  {
    name: 'Petits plats en équilibre',
    start: 1726836900,
    end: 1726837200,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/C4F6912865B1373C99213C2CD41FF1A7.jpg',
    rating: 'Tout public',
    cat: 'Art de vivre',
    desc: 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.',
  },
  {
    name: 'JT 13h',
    start: 1726837200,
    end: 1726839600,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/645660555F4BF0F8EC77C397782FD15C.jpg',
    rating: 'Tout public',
    cat: 'Information',
    desc: 'Retrouvez en replay l\'émission \\" JT 13h Semaine \\" du vendredi 20 septembre 2024.',
  },
  {
    name: 'Petits plats en équilibre',
    start: 1726839600,
    end: 1726839900,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/C4F6912865B1373C99213C2CD41FF1A7.jpg',
    rating: 'Tout public',
    cat: 'Art de vivre',
    desc: 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.',
  },
  {
    name: 'Météo',
    start: 1726839900,
    end: 1726840200,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/5BCD0442D4813EB2EDCBD3E853A866FE.jpg',
    rating: 'Tout public',
    cat: 'Services',
    desc: 'Météo du vendredi 20 septembre 2024 à 13h56 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du vendredi 20 septembre 2024 à 13h56 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.',
  },
  {
    name: 'Plus belle la vie, encore plus belle',
    start: 1726840200,
    end: 1726842000,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/4FFCE28BB96662E1B084F8B31DFBD5F1.jpg',
    rating: 'Tout public',
    cat: 'Série',
    desc: "Dans le groupe des quatre amies, l'une d'entre elle menace de craquer car la pression est trop forte. Toujours incapable de résister à la tentation,",
  },
  {
    name: 'Un professeur trop séduisant',
    start: 1726842000,
    end: 1726847400,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/245C2640E1C765A80D93DF59483F7E24.jpg',
    rating: '-10',
    cat: 'Téléfilm',
    desc: 'Lorsque Nicole Atkins retourne à la fac, elle ne pense plus du tout à son ancienne liaison avec un professeur. Mais sur le campus, une personne qui connaît tous ses secrets la surveille...',
  },
  {
    name: 'Brillante, belle et brisée',
    start: 1726847400,
    end: 1726853400,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/7760865E60CB93E645934F96DE18A7EC.jpg',
    rating: '-10',
    cat: 'Téléfilm',
    desc: "Après une blessure à la jambe, Jenny, une jeune coureuse, a perdu sa bourse d'étude et entre dans une nouvelle université où elle doit faire ses preuves. Elle n'a jamais quitté le cocon familial et se retrouve à vivre sur le campus, dans une petite chambre avec deux autres étudiantes. Rapidement, son prof de psycho semble la prendre en grippe et ne lui met que des mauvaises notes. Beth, une de ses colocs, lui suggère de s'habiller plus sexy pour aller à ses cours, ce qui semble en effet satisfaire le professeur. Mais ce qui n'est pas du tout du goût de Kristen, la mère de Jenny. Dans le même temps, d'étranges morts surviennent sur le campus. Une étudiante meurt en tombant du toit de la résidence et un prof d'histoire est empoisonné...",
  },
  {
    name: 'Familles nombreuses : la vie en XXL',
    start: 1726853400,
    end: 1726857000,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/3C21F3E8FE2AF27A190125E2551AAE39.jpg',
    rating: 'Tout public',
    cat: 'Programme',
    desc: "Clément se remet doucement de son coup de chaud pour entamer l'échange des alliances avec sa future femme. Chez les Philippe, papa et maman ne semblent pas s'accorder sur l'éducation des enfants. Enfin, pendant que les Jean-Zéphirin partent chez l'ophtalmologue, les Fernandes De Bagnolo partent en randonnée. Familles nombreuses : la vie en XXL. Saison 08 Épisode 71.",
  },
  {
    name: 'Ici tout commence',
    start: 1726857000,
    end: 1726859400,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/1914DC8798F05B17321BF1AB60736785.jpg',
    rating: 'Tout public',
    cat: 'Série',
    desc: "Cléo mise tout sur Thibault. A l'Institut, Enzo n'est jamais à court de concepts ! De son côté, Gaspard se fait une nouvelle ennemie.",
  },
  {
    name: 'Demain nous appartient',
    start: 1726859400,
    end: 1726862100,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/5E2C300E141F8FC15FBD88922B95A2FC.jpg',
    rating: 'Tout public',
    cat: 'Série',
    desc: 'Les policiers découvrent la cible du tueur en série. Charles fait une promesse à Valentine. Blessée, Mona fait face à une grosse déception.',
  },
  {
    name: 'Météo',
    start: 1726862100,
    end: 1726862400,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/5BCD0442D4813EB2EDCBD3E853A866FE.jpg',
    rating: 'Tout public',
    cat: 'Services',
    desc: 'Prévisions météorologiques en France par le service de TF1.',
  },
  {
    name: 'JT 20h',
    start: 1726862400,
    end: 1726865100,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/AB67E0AC40E6D75EEB783F5DF6206AF3.jpg',
    rating: 'Tout public',
    cat: 'Information',
    desc: '\\" JT 20h WE \\" du vendredi 20 septembre 2024 à 19h58. Le vendredi à 20h, le samedi et le dimanche, "LE WE" prend le relais des journaux de la semaine ("LE 13H" et "LE 20H"). La rédaction TF1, à travers le jt du weekend continue de vous informer et ainsi met en exergue l\'actualité régionale, nationale et internationale. Le journal du weekend est présenté par Audrey Crespo-Mara',
  },
  {
    name: 'My Million',
    start: 1726865100,
    end: 1726865400,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/0455568DF04F634E6E2840BCF12A7E84.jpg',
    rating: 'Tout public',
    cat: 'Services',
    desc: "Au menu, les derniers résultats d'EuroMillions ainsi que les codes gagnants My Million, avec les 5 numéros gagnants et les 2 bonnes étoiles de la loterie.",
  },
  {
    name: 'Petits plats en équilibre',
    start: 1726865400,
    end: 1726866000,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/F4A4D49AED9904E7ACC78D1FBB8A6CE0.jpg',
    rating: 'Tout public',
    cat: 'Art de vivre',
    desc: 'Laurent Mariotte donne toutes les astuces pour préparer de bons petits plats, comme un vrai chef, avec des ingrédients frais et de saison.',
  },
  {
    name: 'Météo',
    start: 1726866000,
    end: 1726866600,
    channel: 'TF1.fr',
    icon: 'https://img.bouygtel.fr/CMS/images/5BCD0442D4813EB2EDCBD3E853A866FE.jpg',
    rating: 'Tout public',
    cat: 'Services',
    desc: 'Météo du vendredi 20 septembre 2024 à 20h46 sur TF1 présentée par Tatiana Silva ou Evelyne Dheliat. Consultez sans plus attendre les prévisions météorologiques du vendredi 20 septembre 2024 à 20h46 et découvrez les températures du jour, du lendemain et des prochains jours en France métropolitaine et en Corse.',
  },
];
  constructor() { }
  getTVShows(){
    return this.tvShows;
  }
}
